apps/miranum-cli/src/app/deployment/deployment.ts
apps/miranum-console/package.json
apps/miranum-console/src/app/deployment/deployment.ts
apps/miranum-console/src/app/deployment/deploymentAPI.ts
libs/miranum-core/src/lib/generate/plugins.spec.ts
libs/miranum-core/src/lib/generate/plugins.ts

**Issue**
https://www.notion.so/miragon/Configs-werden-als-Forms-deployed-d72ec4a711174b6eb1a330f671ab5f44
**Checklist**

fix/ConfigDeployment: 

---

.github/workflows/build.yml
package.json
spring-boot-apps/miranum-deployment-proxy/miranum-coverage/pom.xml

**Issue**
https://www.notion.so/miragon/Code-Coverage-report-generieren-und-CodeCov-einrichten-873ab65b11ad492985b88edd8f64a796
**Checklist**

feat: codecov

---

.eslintrc.json
package-lock.json
package.json

**Issue**
- Eslint Config angepasst
- Primereact entfernt
**Checklist**

chore: fixed eslint config and lifecycling

---

.github/dependabot.yml
.github/workflows/release.yml

**Issue**
https://www.notion.so/miragon/Dependabot-einrichten-8fec65bad7d542c9bdf341244348f7dc
- Added dependabot
- Lifecycle github actions
**Checklist**

Chore: added dependabot

---

apps/miranum-forms/package.json
apps/miranum-forms/src/app/JsonSchemaBuilderProvider.ts
apps/miranum-forms/src/app/lib/TextEditorWrapper.ts
package-lock.json
package.json

**Issue**
* Buttons are moving when user switches between custom editor and text editor
* https://www.notion.so/miragon/Buttons-f-r-Preview-switches-definieren-und-umsetzen-93b63a9834ca46b396658498fb4bf398?pvs=4
**Checklist**

fix(form-builder): buttons

---

.github/workflows/dry-release.yml
.github/workflows/release.yml

**Issue**
- Added Miranum-Forms to release pipeline
**Checklist**

feat(cicd): added miranum-forms to release pipeline and refactoring

---

.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature.md

**Issue**
https://github.com/FlowSquad/miranum/issues/54
We need issue templates for epics and features in the miranum-ide repository. 
**Checklist**
- not applicable -

feat: adding issue template for epic and feature

---

.github/workflows/release.yml

**Issue**
#None
- Fixed release pipeline
**Checklist**

fix(cicd): release pipeline

---

spring-boot-apps/miranum-deployment-proxy/miranum-deployment-proxy-example/src/main/resources/application.yaml

**Issue**
#None
- Fixed invalid configurations
**Checklist**

fix(deployment-proxy): fix invalid configuration options

---

README.md
apps/miranum-cli/src/README.md
apps/miranum-cli/src/app/generate/api.ts
apps/miranum-console/README.md
apps/miranum-console/package.json
apps/miranum-extension-pack/README.md
apps/miranum-extension-pack/package.json
apps/miranum-forms/README.md
apps/miranum-forms/package.json
apps/miranum-forms/src/app/JsonSchemaBuilderProvider.ts
apps/miranum-modeler/README.md
apps/miranum-modeler/package.json
docs/development.md
docs/quickstart.md
docs/releases.md
libs/miranum-core/README.md
spring-boot-apps/miranum-deployment-proxy/pom.xml

**Issue**
- Renamed git repository links from FlowSquad to Miragon
**Checklist**

chore: rename git repositories

---

apps/miranum-console/CHANGELOG.md
apps/miranum-console/README.md
apps/miranum-console/package.json
apps/miranum-console/project.json
apps/miranum-extension-pack/CHANGELOG.md
apps/miranum-extension-pack/README.md
apps/miranum-extension-pack/package.json
apps/miranum-forms/CHANGELOG.md
apps/miranum-forms/README.md
apps/miranum-forms/package.json
apps/miranum-forms/project.json
apps/miranum-modeler/CHANGELOG.md
apps/miranum-modeler/README.md
apps/miranum-modeler/package.json
apps/miranum-modeler/project.json
docs/releases.md

Adding CHANGELOGs for our extensions to inform users about new features that an update will offer.
**Checklist**

chore(extensions): add changelogs

---

README.md

**Issue**
- fixed shields in README.md
**Checklist**

fix: fix shields in README.md

---

.github/workflows/build.yml

chore: prevent codecov errors from failing the pipeline

---

apps/miranum-console/CHANGELOG.md
apps/miranum-console/README.md
apps/miranum-extension-pack/CHANGELOG.md
apps/miranum-forms/CHANGELOG.md
apps/miranum-modeler/CHANGELOG.md
apps/miranum-modeler/README.md
apps/miranum-modeler/project.json
package-lock.json
package.json

Preparations for next release:
* Update READMEs
* Update CHANGELOGS
* Update package.json
**Checklist**

feat(release): prepare release 0.4.3

---

.editorconfig
.github/workflows/release.yml

**Issue**
- Refactor github release action to use checkboxes
**Checklist**

refactor: update release pipeline to use checkboxes

---

spring-boot-apps/miranum-deployment/pom.xml

chore: bump maven-source-plugin from 3.2.1 to 3.3.0

---

spring-boot-apps/miranum-deployment/miranum-deployment-coverage/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-example/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-embedded-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-service/pom.xml
spring-boot-apps/miranum-deployment/pom.xml

chore: bump spring-boot version from 2.7.11 to 2.7.12

---

.github/workflows/build.yml
.github/workflows/dry-release.yml
.github/workflows/release.yml
spring-boot-apps/miranum-deployment/Dockerfile
spring-boot-apps/miranum-deployment/miranum-deployment-coverage/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-example/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/main/java/io/miragon/miranum/deploymentreceiver/application/dto/DeploymentDto.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/main/java/io/miragon/miranum/deploymentreceiver/application/usecase/DeployFileUseCase.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/test/java/io/miragon/miranum/deploymentreceiver/application/usecase/DeployFileUseCaseTest.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/src/main/java/io/miragon/miranum/deploymentreceiver/adapter/in/rest/DeploymentReceiverController.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/src/main/resources/META-INF/spring.factories
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/src/main/java/io/miragon/miranum/deploymentserver/application/dto/ArtifactDto.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/src/main/java/io/miragon/miranum/deploymentserver/application/dto/DeploymentDto.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/src/main/java/io/miragon/miranum/deploymentserver/application/dto/FileDto.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/src/main/java/io/miragon/miranum/deploymentserver/application/usecase/DeployArtifactUseCase.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/src/test/java/io/miragon/miranum/deploymentserver/application/usecase/DeployArtifactUseCaseTest.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-embedded-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-embedded-starter/src/main/resources/META-INF/spring.factories
spring-boot-apps/miranum-deployment/miranum-deployment-server-embedded-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/src/main/resources/META-INF/spring.factories
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-apps/miranum-deployment/miranum-deployment-service/pom.xml
spring-boot-apps/miranum-deployment/pom.xml

**Issue**
- update miranum-deployment to spring boot 3
**Checklist**

chore: migrate miranum-deployment to spring boot 3

---

apps/miranum-modeler/src/app/BpmnModeler.ts
libs/vscode/miranum-vscode/src/lib/fileSystem/Reader.ts
package-lock.json
package.json
resources/monorepo-example/README.md
resources/monorepo-example/configs/monorepo-example_dev.config.json
resources/monorepo-example/configs/monorepo-example_prod.config.json
resources/monorepo-example/element-templates/mail/mail.template.json
resources/monorepo-example/forms/bar/BarForm.form
resources/monorepo-example/forms/foo/FooForm.form
resources/monorepo-example/forms/mail/email-example-V02_start.form
resources/monorepo-example/miranum.json
resources/monorepo-example/processes/monorepo-example.bpmn
resources/monorepo-example/processes/subprocesses/StreamingTemplateV02.bpmn

**Issue**
* #451 
Collect forms and element templates recursively.
**Checklist**

bug(modeler): recursive search for forms and element templates

---

spring-boot-apps/miranum-deployment/README.md
spring-boot-apps/miranum-deployment/miranum-deployment-coverage/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-example-service/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-example/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-example/src/main/java/io/miragon/miranum/deploymentserver/deployment/ExampleDeploymentReceiver.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/main/java/io/miragon/miranum/deploymentreceiver/adapter/out/MiranumDeploymentReceiverImpl.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/main/java/io/miragon/miranum/deploymentreceiver/application/ports/out/MiranumDeploymentReceiver.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/main/java/io/miragon/miranum/deploymentreceiver/application/usecase/DeployFileUseCase.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-core/src/test/java/io/miragon/miranum/deploymentreceiver/application/usecase/DeployFileUseCaseTest.java
spring-boot-apps/miranum-deployment/miranum-deployment-receiver-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-core/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-embedded-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/pom.xml
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/src/main/java/io/miragon/miranum/deploymentserver/adapter/out/MiranumRestDeployment.java
spring-boot-apps/miranum-deployment/miranum-deployment-server-rest-starter/src/main/java/io/miragon/miranum/deploymentserver/configuration/DeploymentServerRestAutoconfiguration.java
spring-boot-apps/miranum-deployment/pom.xml

**Issue**
https://github.com/it-at-m/digiwf-core/issues/1156
- Enable custom `RequestInterceptor`s
- Enalbe tag support
- Bump version
- Update Dependencies
**Checklist**

feature: support authentication in miranum deployment

---

apps/miranum-jsonforms/package.json
apps/miranum-modeler/src/adapter/out/index.ts
apps/miranum-modeler/src/adapter/out/quickPick.ts
apps/miranum-modeler/src/application/ports/out.ts
apps/miranum-modeler/src/application/useCases/displayEditor.spec.ts
apps/miranum-modeler/src/application/useCases/displayEditor.ts
apps/miranum-modeler/src/main.config.ts

feat(modeler): add quickPick

---

apps/miranum-modeler-bpmn-webview/src/app/modeler.ts
apps/miranum-modeler-bpmn-webview/src/main.ts
apps/miranum-modeler/CHANGELOG.md
apps/miranum-modeler/package.json
apps/miranum-modeler/src/adapter/in/commands.ts
apps/miranum-modeler/src/adapter/out/editor.ts
apps/miranum-modeler/src/application/ports/in.ts
apps/miranum-modeler/src/application/ports/out.ts
apps/miranum-modeler/src/application/useCases/queries.ts
apps/miranum-modeler/src/main.config.ts
apps/miranum-modeler/src/main.ts
libs/vscode/miranum-vscode-webview/src/lib/miranum-modeler.ts
package.json

feat(modeler): add commands to copy or save diagram as svg

---

README.md

Add professional support section to README.md
**Checklist**

docs: add professional support
